[versions]
universalcraft = "365"
elementa = "670"
vigilance = "306"
mixinextras = "0.3.5"

[libraries]
universalcraft-standalone = { module = "gg.essential:universalcraft-standalone", version.ref = "universalcraft" }
elementa = { module = "gg.essential:elementa", version.ref = "elementa" }
vigilance = { module = "gg.essential:vigilance", version.ref = "vigilance" }
# This is the version shipped by MC 1.19.3, the oldest version on which we used the builtin slf4j.
# Do not change this unless you also change on which MC versions we use our relocated slf4j.
# Also note that `SELF4JServiceProviderImpl.getRequestedApiVersion` may need to be updated when this is changed.
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.1" }
